### ISSUE TITLE
"Project" is locked for editing and you will not be able to save your changes.

### ISSUE THREAD

**Issue by chenguohao** [manicmaniac/xcnew#12]
when I create a new project, this awesome tools make it happen. however ,when I open it ,the Xcode show me this alert:
**### "Project" is locked for editing and you will not be able to save your changes.**
“PROJECT2 Project” is currently locked because it does not support editing.

**Comment by manicmaniac** [comment]
@chenguohao Thank you for reporting.
Could I ask which version of Xcode where the problem happens?

**Comment by manicmaniac** [comment]
I just tested with Xcode 11.1 but the problem couldn't be reproduced 🤔

**Comment by chenguohao** [comment]
11.2, I build the project , and run this file in "product" folder

**Comment by manicmaniac** [comment]
@chenguohao

I suppose you created the project in read only folder.
Could you check the newly created project's permission and tell me what happens when you install `xcnew` into a regular folder like `/usr/local/bin`?

**Comment by manicmaniac** [comment]
I tested with Xcode 11.2.1 and it worked fine.

**Comment by manicmaniac** [comment]
Will close this one but feel free to ask me if you have any updates.
